#' Heat plot for network path
#'
#' @description
#' Produces a heat plot to visualize the results of a path-based inconsistency
#' test for a specific comparison, as generated by \code{\link{netpath}}.
#' The plot shows a standardized matrix derived from the linearly independent
#' paths connecting the two selected nodes, allowing visual inspection of the
#' agreement of each path.
#'
#' @param x An object of class \code{netmeta}.
#' @param \dots Additional arguments (ignored).
#' 
#' @return
#' A heat plot where the darker colors indicate a larger conflict between the 
#' two paths. 
#' 
#' @seealso \code{\link{netpath}}, \code{\link{netmeta}}
#' 
#' @references
#' Tahmasebi NR, Davies AL, Papakonstantinou T, Rücker G,
#' Nikolakopoulou A (2025):
#' Path-based approach for detecting and assessing inconsistency in network
#' meta-analysis: A novel method.
#' \emph{arXiv}, \doi{https://doi.org/10.48550/arXiv.2506.20364}
#' 
#' @keywords hplot
#' 
#' @author Noosheen R. Tahmasebi
#'   \email{noosheen.rajabzadehtahmasebi@@uniklinik-freiburg.de},
#'   Guido Schwarzer \email{guido.schwarzer@@uniklinik-freiburg.de}
#' 
#' @examples
#' \dontrun{
#' # Transform data from long arm-based to contrast-based format
#' #
#' pw <- pairwise(studlab = study, treat = treatment,
#'   n = n, mean = mean, sd = sd, data = Senn2013,
#'   varnames = c("MD", "seMD"))
#'
#' # Conduct common effects network meta-analysis
#' #
#' nma <- netmeta(pw, random = FALSE, nchar.trts = 4)
#' 
#' np <- netpath(nma, node1 = "Placebo", node2 = "Sulfonylurea")
#' heatplot(np)
#' }
#'
#' @method heatplot netpath
#' @export

heatplot.netpath <- function(x, ...) {
  chkclass(x, "netpath")
  #
  xhat <- x$theta_p
  Sigma <- x$Sigma
  index <- x$results$path_index
  #
  create_standardized_heatmap(xhat, Sigma, index)  
}
